name: Hybrid3
favicon: null
layout_spectrum: 0.5544354212470353
typography_spectrum: 0.1995344099123031
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.055286062182858586
  lightness: 0.2344524241052568
  saturation: 0.14390991535037756
  rhythmicContrast: 0.653125214856118
purpose: []
